---
image: ruby:2.4.2
stages:
  - build
  - test
  - staging

before_script:
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - bundle install --without system_tests

build:
  stage: build
  script:
    - bundle exec rake build

rubocop:
  stage: test
  script:
    - bundle exec rake rubocop

syntax:
  stage: test
  script:
    - bundle exec rake syntax lint

metadata:
  stage: test
  script:
    - bundle exec rake metadata_lint

spec_puppet_3:
  stage: test
  variables:
    PUPPET_GEM_VERSION: ~> 3.0
    TASK: spec
  script:
    - bundle update
    - bundle exec rake $TASK

spec_puppet_4:
  stage: test
  variables:
    PUPPET_GEM_VERSION: ~> 4.0
    TASK: spec
  script:
    - bundle update
    - bundle exec rake $TASK

spec_puppet_5:
  stage: test
  variables:
    PUPPET_GEM_VERSION: ~> 5.0
    TASK: spec
  script:
    - bundle update
    - bundle exec rake $TASK

